# Generated by Django 5.1.2 on 2024-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='initial_investment',
        ),
        migrations.AddField(
            model_name='investmentsettings',
            name='symbol',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
