# Generated by Django 5.1.2 on 2024-11-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_remove_userprofile_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsettings',
            name='initial_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentsettings',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='market_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_price',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='investmentsettings',
            unique_together={('user_profile', 'symbol')},
        ),
    ]
